classdef Bat_GUI
    %UNTITLED Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
        handles
    end
    
    methods
        function obj = Bat_GUI
            % defind figure
            f = figure('Position',[400 100 800 800],...
                'Units','pixel',...
                'MenuBar', 'none',...'
                'Name','Visulization GUI',...
                'Tag','vis_gui');
            
            % add workspace uimenu
            menu_new = uimenu(f,'Text','Tab',...
                'Tag','uimenu_plot');
            
            % add new uimenu
            menu_new_workspace = uimenu(menu_new,'Text','New',...
                'Tag','uimenu_new_workspace');
            
            % add delete uimenu
            menu_delete_workspace = uimenu(menu_new,'Text','Delete',...
                'Tag','uimenu_delete_workspace');
            
            % add tabgroup
            tabgp = uitabgroup(f,'Position',[.05 .05 .90 .90],...
                'TabLocation','top',...
                'Tag','tabgroup_batch');
            
            % update property
            obj.handles = guihandles(f);
        end
        
        function tab1=addplot(obj)
            
            % create a tab
            tab1 = uitab(obj.handles.tabgroup_batch,'Title','New');
            
            % add an axes on tab
            table1 = uitable(tab1,'Units','normalized',...
                'Position',[0.1 0.25 0.75 0.70],...
                'Tag','table_plot');
            
            % add command plot to a tab
            command = uicontrol('style','Edit',...
                'String','',...,
                'HorizontalAlignment','left',...
                'Parent',tab1,...
                'FontSize',10,...
                'ForegroundColor','g',...
                'FontName', 'Cascadia Code',...
                'Units','normalized',...
                'Position',[0.1 0.07 0.75 0.125],...
                'Max',4,...
                'Backgroundcolor','w',...
                'Tag','txt_command',...
                'Enable','on');
            
            % add plot from table
            apply_command = uicontrol('style','pushButton',...
                'String','To Plot',...,
                'HorizontalAlignment','center',...
                'Parent',tab1,...
                'Units','normalized',...
                'Position',[0.88 0.55 0.10 0.05],...
                'Max',4,...
                'Tag','btn_toplot',...
                'Enable','on');
            
            % add apply_command plot
            apply_command = uicontrol('style','pushButton',...
                'String','Apply',...,
                'HorizontalAlignment','center',...
                'Parent',tab1,...
                'Units','normalized',...
                'Position',[0.88 0.15 0.10 0.05],...
                'Max',4,...
                'Tag','txt_apply',...
                'Enable','on');
            
            % add save_command plot
            save_command = uicontrol('style','pushButton',...
                'String','Save...',...,
                'HorizontalAlignment','center',...
                'Parent',tab1,...
                'Units','normalized',...
                'Position',[0.88 0.10 0.10 0.05],...
                'Max',4,...
                'Tag','txt_save',...
                'Enable','on');
            
            % add load_command plot
            load_command = uicontrol('style','pushButton',...
                'String','Load...',...,
                'HorizontalAlignment','center',...
                'Parent',tab1,...
                'Units','normalized',...
                'Position',[0.88 0.05 0.10 0.05],...
                'Max',4,...
                'Tag','txt_load',...
                'Enable','on');
            % add path display
            path = uicontrol('style','text',...
                'String','path:',...,
                'HorizontalAlignment','left',...
                'Parent',tab1,...
                'Units','normalized',...
                'Position',[0.1 0.01 0.75 0.05],...
                'Max',4,...
                'Tag','txt_path',...
                'Enable','on');
            
        end
        
        function deletework(obj)
            % create gui
            tabgp = obj.handles.tabgroup_batch;
            
            % check selected tab
            tabgp.SelectedTab.Parent=[];
        end
        
        
    end
end

