classdef SetVar
    %UNTITLED Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
        alias
        text
        handles
    end
    
    methods
        function obj = SetVar(a,varargin)
            narginchk(1,2)
            try
                obj.alias = a.alias;
                obj.text = a.text;
                %                     allno=length(a.alias);
            catch
                obj.alias = {''};
                obj.text = {''};
                %                 allno = 1;
            end
            
            if length(varargin)==1
                new = varargin{1};
                obj.alias = [obj.alias,new.alias];
                obj.text = [obj.text,new.text];
            end
            
        end
        function f = addVar(obj,f)
            
            %             if Or(isempty(obj.alias(i)),isempty(obj.text(i)))
            %                 obj.alias(i) = '';
            %                 obj.text(i) = '';
            %             else
            %             end
            allno = 1;
            width = 500;
            height_no = 50;
            height_total = height_no + allno*(height_no+1);
            f = figure('Position',[400 200 width height_total],...
                'Units','pixel',...
                'MenuBar', 'none',...'
                'Name','Preview Variables',...
                'Tag','setvar_gui');
            
            % non-trivial strings
            uicontrol('Parent',f,...
                'style','text',...
                'String','Alias',...
                'HorizontalAlignment','left',...
                'FontSize',10,...
                'Units','pixel',...
                'Position',[50 height_total-25*2 50 25],...
                'Max',1,...
                'Enable','on');
            uicontrol('Parent',f,...
                'style','text',...
                'String','Formula',...
                'HorizontalAlignment','left',...
                'FontSize',10,...
                'Units','pixel',...
                'Position',[100 height_total-25*2 300 25],...
                'Max',1,...
                'Enable','on');
            no=1;
            text_var_alias = uicontrol('Parent',f,...
                'style','edit',...
                'String',obj.alias(no),...
                'HorizontalAlignment','left',...
                'FontSize',10,...
                'Units','pixel',...
                'backgroundColor' ,[0.9400    0.9400    0.9400],...
                'Position',[50 height_total-25*2-(height_no*no-12.5) 35 25],...
                'Max',4,...
                'Tag','txt_var_alias',...
                'Enable','on');
            text_var_text = uicontrol('Parent',f,...
                'style','edit',...
                'String',obj.text(no),...
                'HorizontalAlignment','left',...
                'FontSize',10,...
                'Units','pixel',...
                'backgroundColor' ,[0.9400    0.9400    0.9400],...
                'Position',[100 height_total-25*2-(height_no*no-12.5) 300 25],...
                'Max',4,...
                'Tag','txt_var_text',...
                'Enable','on');
            btn_var_apply= uicontrol('Parent',f,...
                'style','pushbutton',...
                'String','Apply',...
                'HorizontalAlignment','center',...
                'FontSize',10,...
                'Units','pixel',...
                'Position',[400 height_total-25*2-(height_no*no-12.5) 75 25],...
                'Max',1,...
                'Tag','txt_var_apply',...
                'Enable','on',...,
                'UserData',no);
            %             guidata(f,btn_var_apply)
            
            
            
        end
        
        
        function f = GUI_ShowVar(obj,varargin)
            
            narginchk(1,2)
            
            
            % define figure
            allno = length(obj.alias);
            
            % window size properties
            width = 500;
            height_no = 50;
            height_total = height_no + allno*(height_no+1);
            if length(varargin)==1 % update figure
                f = varargin{1};
                set(f,'Position',[400 200 width height_total],...
                    'Units','pixel',...
                    'MenuBar', 'none',...'
                    'Name','Preview Variables',...
                    'Tag','setvar_gui');
%                 f.Children.delete
                delete(findobj('Type', 'UIControl'))
                % add new uimenu
            else
                % create new figure
                f = figure('Position',[400 200 width height_total],...
                    'Units','pixel',...
                    'MenuBar', 'none',...'
                    'Name','Preview Variables',...
                    'Tag','setvar_gui');
                % add new uimenu
                menu_new_var = uimenu(f,'Text','Add..',...
                    'Tag','uimenu_add_var');
            end
            
            
            
            % non-trivial strings
            uicontrol('Parent',f,...
                'style','text',...
                'String','Alias',...
                'HorizontalAlignment','left',...
                'FontSize',10,...
                'Units','pixel',...
                'Position',[50 height_total-25*2 50 25],...
                'Max',1,...
                'Enable','on');
            uicontrol('Parent',f,...
                'style','text',...
                'String','Formula.',...
                'HorizontalAlignment','left',...
                'FontSize',10,...
                'Units','pixel',...
                'Position',[100 height_total-25*2 300 25],...
                'Max',1,...
                'Enable','on');
            
            % add default preview for the first one
            for no=1:allno
                text_var_alias(no) = uicontrol('Parent',f,...
                    'style','text',...
                    'String',obj.alias(no),...
                    'HorizontalAlignment','left',...
                    'FontSize',10,...
                    'Units','pixel',...
                    'backgroundColor' ,[0.9400    0.9400    0.9400],...
                    'Position',[50 height_total-25*2-(height_no*no-12.5) 35 25],...
                    'Max',4,...
                    'Tag','txt_var_alias_%d',...
                    'Enable','on');
                text_var_text(no) = uicontrol('Parent',f,...
                    'style','text',...
                    'String',obj.text(no),...
                    'HorizontalAlignment','left',...
                    'FontSize',10,...
                    'Units','pixel',...
                    'backgroundColor' ,[0.9400    0.9400    0.9400],...
                    'Position',[100 height_total-25*2-(height_no*no-12.5) 300 25],...
                    'Max',4,...
                    'Tag',sprintf('txt_var_text_%d',no),...
                    'Enable','on');
                btn_var_apply(no) = uicontrol('Parent',f,...
                    'style','pushbutton',...
                    'String','Edit',...
                    'HorizontalAlignment','center',...
                    'FontSize',10,...
                    'Units','pixel',...
                    'Position',[400 height_total-25*2-(height_no*no-12.5) 75 25],...
                    'Max',4,...
                    'Tag',sprintf('txt_var_edit_%d',no),...
                    'Enable','on',...
                    'UserData',no);
                %             guidata(f,btn_var_apply)
                
            end
            
            %             text_var_text(:).String;
            %             obj.alias = {'assssss'};
            %             obj.text = {'tesss'};
            % update handles to obj properties
            
            
            %             function edit(hObject,evendata,handles)
            %                 index = get(hObject,'UserData');
            %                 if or(get(text_var_text(index),'style')=='text',get(text_var_alias(index),'style')=='text')
            %                     set(text_var_text(index),'style','edit','backgroundColor' ,'white');
            %                     set(text_var_alias(index),'style','edit','backgroundColor' ,'white');
            %                     set(hObject,'String','Apply')
            %                 else
            %                     set(text_var_text(index),'style','text','backgroundColor' ,[0.9400    0.9400    0.9400]);
            %                     set(text_var_alias(index),'style','text','backgroundColor' ,[0.9400    0.9400    0.9400]);
            %                     set(hObject,'String','Edit');
            %                 end
            %                 %                disp(text_var_text(index).String);
            %                 guidata(f,text_var_alias(index))
            %                 guidata(f,text_var_text(index))
            %
            %                 obj.alias = [text_var_alias(:).String];
            %                 obj.text = [text_var_text(:).String];
            %             end
            
        end
    end
    
end