classdef Vis_GUI
    
    %UNTITLED Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
        handles
        %         addplottab
    end
    
    methods
        function obj = Vis_GUI
            % defind figure
            f = figure('Position',[300 20 800 800],...
                'Units','pixel',...
                'MenuBar', 'none',...'
                'Name','Visulization GUI',...
                'Tag','vis_gui');
            
            % add workspace uimenu
            menu_new = uimenu(f,'Text','Tab',...
                'Tag','uimenu_plot');
            
            % add unit convertor
            menu_unit_setting = uimenu(f,'Text','Unit setting',...
                'Tag','uimenu_unit_setting');
            
            % add new uimenu
            menu_new_workspace = uimenu(menu_new,'Text','New',...
                'Tag','uimenu_new_workspace');
            
            % add delete uimenu
            menu_delete_workspace = uimenu(menu_new,'Text','Delete',...
                'Tag','uimenu_delete_workspace');
            
            % add tabgroup
            tabgp = uitabgroup(f,'Position',[.05 .05 .90 .90],...
                'TabLocation','top',...
                'Tag','tabgroup_plot');
            
            % update property
            obj.handles = guihandles(f);
        end
        
        function tab1=addplot(obj)
            
            % create a tab
            tab1 = uitab(obj.handles.tabgroup_plot,'Title','New');
            
            % add an axes on tab
            axes1 = axes(tab1,'Position',[0.1 0.30 0.75 0.65],...
                'Tag','axes_plot');
            
            % add condition to a tab
            condition = uicontrol('style','Edit',...
                'String','',...,
                'HorizontalAlignment','left',...
                'Parent',tab1,...
                'FontSize',10,...
                'ForegroundColor','r',...
                'FontName', 'Cascadia Code',...
                'Units','normalized',...
                'Position',[0.20 0.19 0.65 0.040],...
                'Max',1,...
                'Backgroundcolor','k',...
                'Tag','txt_condition',...
                'Enable','on');
            
            % add text condition
            text_condition = uicontrol('style','text',...
                'String','Condition :',...,
                'HorizontalAlignment','right',...
                'FontSize',10,...
                'FontWeight','bold',...
                'ForegroundColor','r',...
                'Parent',tab1,...
                'Units','normalized',...
                'Position',[0.1 0.19 0.10 0.04],...
                'Max',4,...
                'Tag','txt_c',...
                'Enable','on');
            
            % add command plot to a tab
            command = uicontrol('style','Edit',...
                'String','',...,
                'HorizontalAlignment','left',...
                'Parent',tab1,...
                'FontSize',10,...
                'ForegroundColor','g',...
                'FontName', 'Cascadia Code',...
                'Units','normalized',...
                'Position',[0.20 0.08 0.35 0.105],...
                'Max',4,...
                'Backgroundcolor','k',...
                'Tag','txt_command',...
                'Enable','on');
            
            % add option plot to a tab
            command = uicontrol('style','Edit',...
                'String','',...,
                'HorizontalAlignment','left',...
                'Parent',tab1,...
                'FontSize',10,...
                'ForegroundColor','g',...
                'FontName', 'Cascadia Code',...
                'Units','normalized',...
                'Position',[0.55 0.08 0.30 0.105],...
                'Max',4,...
                'Backgroundcolor','k',...
                'Tag','txt_option',...
                'Enable','on');
            
            % add text plot
            text_command = uicontrol('style','text',...
                'String','Plot :',...,
                'HorizontalAlignment','right',...
                'FontSize',10,...
                'FontWeight','bold',...
                'ForegroundColor','g',...
                'Parent',tab1,...
                'Units','normalized',...
                'Position',[0.1 0.15 0.10 0.04],...
                'Max',4,...
                'Tag','txt_p',...
                'Enable','on');
            
            % add apply_command plot
            apply_command = uicontrol('style','pushButton',...
                'String','Apply',...,
                'HorizontalAlignment','center',...
                'Parent',tab1,...
                'Units','normalized',...
                'Position',[0.88 0.18 0.10 0.05],...
                'Max',4,...
                'Tag','txt_apply',...
                'Enable','on');
            
            % add save_command plot
            save_command = uicontrol('style','pushButton',...
                'String','Save...',...,
                'HorizontalAlignment','center',...
                'Parent',tab1,...
                'Units','normalized',...
                'Position',[0.88 0.13 0.10 0.05],...
                'Max',4,...
                'Tag','txt_save',...
                'Enable','on');
            
            % add load_command plot
            load_command = uicontrol('style','pushButton',...
                'String','Load...',...,
                'HorizontalAlignment','center',...
                'Parent',tab1,...
                'Units','normalized',...
                'Position',[0.88 0.08 0.10 0.05],...
                'Max',4,...
                'Tag','txt_load',...
                'Enable','on');
            % add path display
            path = uicontrol('style','text',...
                'String','path:',...,
                'HorizontalAlignment','left',...
                'Parent',tab1,...
                'Units','normalized',...
                'Position',[0.20 0.01 0.75 0.05],...
                'Max',4,...
                'Tag','txt_path',...
                'Enable','on');
            
        end
        
        function deletework(obj)
            % create gui
            tabgp = obj.handles.tabgroup_plot;
            
            % check selected tab
            tabgp.SelectedTab.Parent=[];
        end
        
        function f = unit_conversion(obj, objbeam)
            % create GUI class for input
            num_unit = length(fieldnames(objbeam.unit));
            f= figure( ...
                'Tag', 'figure1', ...
                'Units', 'pixels', ...
                'Position', [500 500 260 num_unit*40], ...
                'Name', 'Unit Convertor', ...
                'MenuBar', 'none', ...
                'NumberTitle', 'off', ...
                'Color', get(0,'DefaultUicontrolBackgroundColor'),...
                'Tag','unit_conv');
            
            fieldunit = fieldnames(objbeam.unit);
            objbeam.unit.x
            % static texts
            ypos = num_unit*40-40;
            textstring = fieldunit;                        
            currentunit_tag = cellfun(@(ss) sprintf('popup_%s',ss),fieldunit,'UniformOutput',0);
            
            for i=1:num_unit
                 uicontrol( ...
                'Parent', f, ...
                'Style', 'text', ...
                'Units', 'pixels', ...
                 'Position', [20 ypos 80 28], ...
                'FontName', 'Arial', ...
                'FontSize', 12, ...
                'FontWeight', 'bold', ...
                'String', textstring{i}, ...
                'HorizontalAlignment', 'right');
            
                uicontrol( ...
                'Parent', f, ...
                'Tag', currentunit_tag{i}, ...
                'Style', 'text', ...
                'Units', 'pixels', ...
                'Position', [120 ypos 120 28], ...
                'FontName', 'Arial', ...
                'FontSize', 12, ...
                'FontWeight', 'bold', ...
                'String', getfield(objbeam.unit,textstring{i}));
            ypos = ypos - 40;
            end
            
            % update property
%             obj.handles = guihandles(f);
        end
    end
end

